# Generated by Django 4.2.18 on 2025-01-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_num", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="processed_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_images",
                        to="user.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
