# Generated by Django 5.1.6 on 2025-10-22 07:32

import document_processor.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedimage",
            name="image",
            field=models.ImageField(
                storage=document_processor.storages_backends.AzureMediaStorage(),
                upload_to="processed_files/",
            ),
        ),
        migrations.AlterField(
            model_name="processedpdf",
            name="file_path",
            field=models.FileField(
                storage=document_processor.storages_backends.AzureMediaStorage(),
                upload_to="processed_img_pdf/",
            ),
        ),
    ]
