# Generated by Django 5.1.6 on 2025-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_processedpdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedimage",
            name="is_split",
            field=models.BooleanField(default=False),
        ),
    ]
