# Generated by Django 5.1.6 on 2025-10-22 03:23

import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_processedimage_is_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedimage",
            name="image",
            field=models.ImageField(upload_to=document.models.processed_image_path),
        ),
        migrations.AlterField(
            model_name="processedpdf",
            name="file_path",
            field=models.FileField(upload_to=document.models.processed_pdf_path),
        ),
    ]
