# Generated by Django 5.1.5 on 2025-01-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_emailusermapping"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailUserMapping",
        ),
    ]
