# Generated by Django 5.1.5 on 2025-02-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_delete_emailusermapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="file_created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="is_archieved",
            field=models.BooleanField(default=False),
        ),
    ]
