# Generated by Django 5.1.6 on 2025-10-22 06:45

import user.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_uploadedfile_file_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="file_created_at",
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                storage=user.storages_backends.AzureMediaStorage(), upload_to="uploads/"
            ),
        ),
    ]
