# Generated by Django 5.1.6 on 2025-10-22 03:23

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_uploadedfile_file_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to=user.models.user_upload_path),
        ),
    ]
